# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='immune',
            field=models.ManyToManyField(related_name='_type_immune_+', to='pokedex.Type'),
        ),
    ]
