# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_type_immune'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='immune',
        ),
        migrations.RemoveField(
            model_name='type',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='type',
            name='weaknesses',
        ),
        migrations.AddField(
            model_name='type',
            name='immune_to',
            field=models.ManyToManyField(related_name='_type_immune_to_+', to='pokedex.Type'),
        ),
        migrations.AddField(
            model_name='type',
            name='strong_attack',
            field=models.ManyToManyField(related_name='_type_strong_attack_+', to='pokedex.Type'),
        ),
        migrations.AddField(
            model_name='type',
            name='strong_defense',
            field=models.ManyToManyField(related_name='_type_strong_defense_+', to='pokedex.Type'),
        ),
        migrations.AddField(
            model_name='type',
            name='weak_attack',
            field=models.ManyToManyField(related_name='_type_weak_attack_+', to='pokedex.Type'),
        ),
        migrations.AddField(
            model_name='type',
            name='weak_defense',
            field=models.ManyToManyField(related_name='_type_weak_defense_+', to='pokedex.Type'),
        ),
    ]
